### ISSUE TITLE
It's not secure to use Access Token, ClientId and Client Secret on the client

### ISSUE THREAD

**Issue by nicolake** [BMKeros/mercadopago_sdk_dart#20]
Those secret credentials should be used on the server side.
anyone can access to this sensitive data if decompile the apk

**Comment by brendabullorini** [comment]
> Those secret credentials should be used on the server side.
> anyone can access to this sensitive data if decompile the apk

Y cuál es el problema? sólo tenes que hacer una API para traerlas del server. No están hardcodeadas en el código

**Comment by hostelix** [comment]
Yes, is not secure use secret key in app mobile

**Comment by neoacevedo** [comment]
PING.
