### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by marianoarga** [BMKeros/mercadopago_sdk_dart#21]
Is this plugin ready for iOS? it says so in pub.dev, but I dont see any way it can be implemented.

Thanks.

**Comment by ManuLpz4** [comment]
I'm not sure, but I think that yes because it isn't a 'px' solution like the [mercado_pago_mobile_checkout package](https://pub.dev/packages/mercado_pago_mobile_checkout).

If you can, try it and let us know :)

**Comment by marianoarga** [comment]
> I'm not sure, but I think that yes because it isn't a 'px' solution like the [mercado_pago_mobile_checkout package](https://pub.dev/packages/mercado_pago_mobile_checkout).
> 
> If you can, try it and let us know :)

Si Manu, termine usando ese al final ayer, para el final de la compra (checkout) en iOS, y este lo segui conservando (porque ya lo estaba usando antes), gracias igualmente viejo!

**Comment by ManuLpz4** [comment]
De nada!
