### ISSUE TITLE
Public key and access token

### ISSUE THREAD

**Issue by eugenio-tesio** [BMKeros/mercadopago_sdk_dart#24]
According MercadoPago documentation to generate a preference, you need a Public Key and Access Token and not a Client Id and Client Secret.

I tried to get preference sending using de constructor MP('public_key','access_token') but didn't work, so i suppose that the Client id is not the same as Public Key and Client Secret is not the same as Access Token.

**Comment by hostelix** [comment]
@eugenio-tesio Of course! but this sdk is not only to create preferences, it is used for other purposes! client id and client secret used for generate accesstoken  automatically, 
check code!

you can use the factory fromAccessToken
use SDK with only accesstoken
`var mp = MP.fromAccessToken("TOKEN");`
