### ISSUE TITLE
Error of integration using analyzer

### ISSUE THREAD

**Issue by LDHrez** [BMKeros/mercadopago_sdk_dart#29]
Because mercadopago_sdk >=1.3.0 depends on test ^1.16.8 which depends on analyzer ^1.0.0, mercadopago_sdk >=1.3.0 requires analyzer ^1.0.0.

So, because audasiuz depends on both analyzer ^0.40.6 and mercadopago_sdk ^1.3.0, version solving failed.
pub get failed (1; So, because audasiuz depends on both analyzer ^0.40.6 and mercadopago_sdk ^1.3.0, version solving failed.)

**Comment by hostelix** [comment]
upgrade your package audasiuz
